//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2.AppDate
{
    using System;
    using System.Collections.Generic;
    
    public partial class LikeRecipes
    {
        public int LikeID { get; set; }
        public int RecipeID { get; set; }
        public int authorID { get; set; }
    
        public virtual Authors Authors { get; set; }
        public virtual Recipes Recipes { get; set; }
    }
}
